# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

cat1 = Category.create(name: 'Art')
cat2 = Category.create(name: 'Cooking')
cat3 = Category.create(name: 'Dance')
cat4 = Category.create(name: 'Healthy Living')
cat5 = Category.create(name: 'Language')
cat6 = Category.create(name: 'Martial Arts')
cat7 = Category.create(name: 'Music')
cat8 = Category.create(name: 'Plants and Things')
cat9 = Category.create(name: 'Tech')
cat10 = Category.create(name: 'Other')





art1 = Subcategory.create(name:'Painting', category_id: cat1.id)
art2 = Subcategory.create(name:'Crafts', category_id: cat1.id)
art3 = Subcategory.create(name:'Photography', category_id: cat1.id)
art4 = Subcategory.create(name:'Drawing', category_id: cat1.id)
art5 = Subcategory.create(name:'Oils', category_id: cat1.id)
art6 = Subcategory.create(name:'Water Colour', category_id: cat1.id)
art7 = Subcategory.create(name:'Ceramic', category_id: cat1.id)
art8 = Subcategory.create(name:'Stained-glass', category_id: cat1.id)

cook1 = Subcategory.create(name:'Baking', category_id: cat2.id)
cook2 = Subcategory.create(name:'Vegan', category_id: cat2.id)
cook3 = Subcategory.create(name:'Vegetarian', category_id: cat2.id)
cook4 = Subcategory.create(name:'Paleo', category_id: cat2.id)
cook5 = Subcategory.create(name:'Ethnic', category_id: cat2.id)
cook2 = Subcategory.create(name:'Meal Prep', category_id: cat2.id)
cook2 = Subcategory.create(name:'Everyday Cooking', category_id: cat2.id)

dance1 = Subcategory.create(name: 'Ballet', category_id: cat3.id)
dance2 = Subcategory.create(name: 'Jazz', category_id: cat3.id)
dance3 = Subcategory.create(name: 'Tap', category_id: cat3.id)
dance4 = Subcategory.create(name: 'Hiphop', category_id: cat3.id)
dance5 = Subcategory.create(name: 'Modern', category_id: cat3.id)
dance6 = Subcategory.create(name: 'Hiphop', category_id: cat3.id)
dance7 = Subcategory.create(name: 'Modern', category_id: cat3.id)
dance8 = Subcategory.create(name: 'Salsa', category_id: cat3.id)
dance9 = Subcategory.create(name: 'Tango', category_id: cat3.id)

healthy1 = Subcategory.create(name:'Yoga', category_id: cat4.id)
healthy2 = Subcategory.create(name:'Pilates', category_id: cat4.id)
healthy3 = Subcategory.create(name:'Meditation', category_id: cat4.id)
healthy4 = Subcategory.create(name:'Zumba', category_id: cat4.id)
healthy5 = Subcategory.create(name:'Personal Trainers', category_id: cat4.id)
healthy6 = Subcategory.create(name:'Flexibility', category_id: cat4.id)
healthy7 = Subcategory.create(name:'RMT', category_id: cat4.id)
healthy8 = Subcategory.create(name:'Head Doctors', category_id: cat4.id)

language1 = Subcategory.create(name:'English', category_id: cat5.id)
language2 = Subcategory.create(name:'Spanish', category_id: cat5.id)
language3 = Subcategory.create(name:'French', category_id: cat5.id)
language4 = Subcategory.create(name:'Arabic', category_id: cat5.id)
language5 = Subcategory.create(name:'Hindi', category_id: cat5.id)
language6 = Subcategory.create(name:'Urdu', category_id: cat5.id)
language7 = Subcategory.create(name:'Farsi', category_id: cat5.id)
language8 = Subcategory.create(name:'Mandarin', category_id: cat5.id)
language9 = Subcategory.create(name:'Japanese', category_id: cat5.id)
language10 = Subcategory.create(name:'Cantonese', category_id: cat5.id)
language11 = Subcategory.create(name:'Italian', category_id: cat5.id)
language12 = Subcategory.create(name:'Portuguese', category_id: cat5.id)
language13 = Subcategory.create(name:'Russian', category_id: cat5.id)
language14 = Subcategory.create(name:'Other', category_id: cat5.id)

ma1 = Subcategory.create(name:'Karate', category_id: cat6.id)
ma2 = Subcategory.create(name:'Kung-fu', category_id: cat6.id)
ma3 = Subcategory.create(name:'Kick-boxing', category_id: cat6.id)
ma4 = Subcategory.create(name:'MMA', category_id: cat6.id)
ma5 = Subcategory.create(name:'Taekwondo', category_id: cat6.id)
ma6 = Subcategory.create(name:'Boxing', category_id: cat6.id)
ma7 = Subcategory.create(name:'Brazilian Jiu-Jitsu', category_id: cat6.id)
ma8 = Subcategory.create(name:'Jit-Jitsu', category_id: cat6.id)
ma9 = Subcategory.create(name:'Judo', category_id: cat6.id)
ma10 = Subcategory.create(name:'Muay Thai', category_id: cat6.id)
ma11 = Subcategory.create(name:'Krav Maga', category_id: cat6.id)

music1 = Subcategory.create(name:'Singing', category_id: cat7.id)
music2 = Subcategory.create(name:'Piano', category_id: cat7.id)
music3 = Subcategory.create(name:'Guitar', category_id: cat7.id)
music4 = Subcategory.create(name:'Sax', category_id: cat7.id)
music5 = Subcategory.create(name:'Trumpet', category_id: cat7.id)
music6 = Subcategory.create(name:'Fiddle/Violin', category_id: cat7.id)
music7 = Subcategory.create(name:'Banjo', category_id: cat7.id)
music8 = Subcategory.create(name:'World Instruments', category_id: cat7.id)
music9 = Subcategory.create(name:'Drums', category_id: cat7.id)
music10 = Subcategory.create(name:'Other', category_id: cat7.id)


plant1 = Subcategory.create(name:'Plants & Trees', category_id: cat8.id)
plant2 = Subcategory.create(name:'Grow-Your-Own', category_id: cat8.id)
plant3 = Subcategory.create(name:'Flowers', category_id: cat8.id)
plant4 = Subcategory.create(name:'Care', category_id: cat8.id)
plant5 = Subcategory.create(name:'Terrariums', category_id: cat8.id)

tech1 = Subcategory.create(name:'Graphic Design', category_id: cat9.id)
tech2 = Subcategory.create(name:'Web Design', category_id: cat9.id)
tech3 = Subcategory.create(name:'Mobile App', category_id: cat9.id)
tech4 = Subcategory.create(name:'Tech Help', category_id: cat9.id)
tech5 = Subcategory.create(name:'Programming', category_id: cat9.id)
tech6 = Subcategory.create(name:'Game Development', category_id: cat9.id)
tech7 = Subcategory.create(name:'Machine Learning/A.I.', category_id: cat9.id)
tech8 = Subcategory.create(name:'Digital Marketing', category_id: cat9.id)

other1 = Subcategory.create(name:'Other', category_id: cat10.id)
